
// The seatin package correlates a given hero to his
// defender quality. Note: this is based on seatin's 
// defender ranking, but modified given my opinion
// and was not created with any direct input from seatin
package globals

import "fmt"

var Nodes = map[int][]HeroVal {
  1: []HeroVal{MaxHeroVal},
  2: []HeroVal{HitMonkey, Darkhawk, EbonyMaw},
  3: []HeroVal{MaxHeroVal},
  4: []HeroVal{DoctorVoodoo, Hulkbuster, Cable, Wolverine, ManThing, MaxHeroVal},
  5: []HeroVal{MaxHeroVal},
  6: []HeroVal{Hercules, Medusa, Venom, MaxHeroVal},
  7: []HeroVal{KittyPryde, AbominationImmortal, Punisher2099, MaxHeroVal},
  8: []HeroVal{MaxHeroVal},
  9: []HeroVal{KittyPryde, MaxHeroVal},
  10: []HeroVal{MaxHeroVal},
  11: []HeroVal{ProfessorX, HitMonkey, Darkhawk, JabariPanther, Magneto},
  12: []HeroVal{Domino, MaxHeroVal},
  13: []HeroVal{MoleMan, HulkImmortal, MaxHeroVal},
  14: []HeroVal{NickFury, JabariPanther, Mysterio, MaxHeroVal},
  15: []HeroVal{Wasp, Mysterio, MaxHeroVal},
  16: []HeroVal{MaxHeroVal},
  17: []HeroVal{Hyperion, Venom, SymbioteSupreme, Colossus, Aegon},
  18: []HeroVal{Apocalypse, Thing, DareDevil, JabariPanther},
  19: []HeroVal{Mordo, Wasp, Taskmaster, Medusa, JabariPanther, ProfessorX},
  20: []HeroVal{Tigra, BlackWidowDeadlyOrigins, MaxHeroVal},
  21: []HeroVal{Void, MaxHeroVal},
  22: []HeroVal{VisionAarkus, Korg, Terrax, AirWalker, EbonyMaw},
  23: []HeroVal{Bishop, Apocalypse, Korg, EbonyMaw},
  24: []HeroVal{Thing, Warlock, Terrax, Dragonman, MaxHeroVal},
  25: []HeroVal{Mojo, AirWalker, Thing, Domino},
  26: []HeroVal{Void, Quake, Guillotine2099, Mangog, SorcererSupreme, ScarletWitch, Sentinel, Nova},
  27: []HeroVal{SpiderHam, Annihilus, Havok, SilverSurfer, BlackWidowClaireVoyant, MisterFantastic},
  28: []HeroVal{Iceman, Mephisto, MaxHeroVal},
  29: []HeroVal{Nova, ThorRagnarok, MisterNegative},
  30: []HeroVal{MisterSinister, ManThing, Sabretooth, MaxHeroVal},
  31: []HeroVal{MaxHeroVal},
  32: []HeroVal{CosmicGhostRider, Colossus, Hulkbuster, MaxHeroVal},
  33: []HeroVal{Stryfe, Hyperion, HitMonkey, Killmonger, Bishop, OmegaRed, MaxHeroVal},
  34: []HeroVal{Kingpin, Iceman, Havok, Annihilus, MaxHeroVal},
  35: []HeroVal{Modok, Nightcrawler, Thing},
  36: []HeroVal{Havok, SpiderHam, InvisibleWoman, Annihilus, MisterFantastic, SilverSurfer},
  37: []HeroVal{Nova, ThorRagnarok, MisterNegative, MaxHeroVal},
  38: []HeroVal{Sentinel, Longshot, Dormammu},
  39: []HeroVal{Sasquatch, AbominationImmortal, Kingpin},
  40: []HeroVal{DoctorDoom, HitMonkey, Mysterio},
  41: []HeroVal{Thing, BlackWidowClaireVoyant, MaxHeroVal},
  42: []HeroVal{Modok, IronManInfinityWar, Nightcrawler, MaxHeroVal},
  43: []HeroVal{Apocalypse, Punisher2099, VisionAarkus, Hyperion, OmegaRed},
  44: []HeroVal{Medusa, Odin, Venom, Aegon, MaxHeroVal},
  45: []HeroVal{Dragonman, Mojo, Nightcrawler},
  46: []HeroVal{Tigra, Warlock, Sentinel},
  47: []HeroVal{Terrax, Apocalypse, Tigra, Thing},
  48: []HeroVal{IronManInfinityWar, Korg, NickFury},
  49: []HeroVal{Killmonger, Havok},
  50: []HeroVal{Guillotine2099, Sasquatch, ManThing, Sabretooth},
  51: []HeroVal{NickFury, SpiderHam, Mysterio, JabariPanther},
  52: []HeroVal{Dragonman, Terrax},
  53: []HeroVal{Mangog, Thing, Dragonman},
  54: []HeroVal{Longshot, DoctorDoom, SorcererSupreme, Terrax},
  55: []HeroVal{SpiderGwen, SpiderHam, BlackWidowDeadlyOrigins, DoctorDoom},
}

var levels = map[HeroVal]int { 
    Abomination : 3,
    AgentVenom : 1,
    Angela : 2,
    AntMan : 2,
    ArchAngel : 1,
    Beast : 0,
    BlackBolt : 0,
    BlackPanther : 0,
    BlackPantherCivilWar : 2,
    BlackWidow : 2,
    Cable : 2,
    CaptainAmerica : 0,
    CaptainAmericaWWII : 0,
    CaptainMarvel : 0,
    Carnage : 2,
    CivilWarrior : 0,
    Colossus : 2,
    Crossbones : 4,
    Cyclops : 0,
    CyclopsNew : 0,
    DareDevil : 2,
    DareDevilClassic : 0,
    Deadpool : 0,
    DeadpoolX : 0,
    DoctorStrange : 2,
    DoctorVoodoo: 1,
    Dormammu : 4,
    Drax : 0,
    Elektra : 0,
    Electro : 3,
    Falcon : 1,
    Gambit : 2,
    Gamora : 2,
    GhostRider : 1,
    GreenGoblin : 2,
    Groot : 1,
    Guillotine: 0,
    Gwenpool : 1,
    Hawkeye : 1,
    HowardTheDuck : 2,
    Hulk : 2,
    Hulkbuster : 3,
    Hyperion : 4,
    Iceman : 3,
    IronFist : 0,
    IronFistImmortal : 0,
    IronMan : 0,
    IronPatriot : 0,
    JoeFixit : 0,
    Juggernaut : 2,
    KamalaKhan : 0,
    Kang : 2,
    Karnak : 2,
    Loki : 2,
    LukeCage : 0,
    Magik : 3,
    Magneto : 2,
    MagnetoNow : 1,
    MilesMorales : 1,
    MoonKnight : 0,
    Mordo : 3,
    MsMarvel : 0,
    Nightcrawler : 3,
    OldManLogan : 0,
    Phoenix : 1,
    Psylocke : 1,
    Punisher : 2,
    Punisher2099 : 2,
    Quake : 2,
    RedHulk : 2,
    Rhino : 3,
    RocketRaccoon : 0,
    Rogue : 3,
    Ronan : 0,
    ScarletWitch : 1,
    SheHulk : 0,
    SpiderGwen : 4,
    Spiderman : 2,
    SpidermanSymbiote : 1,
    SpidermanStark : 2,
    StarLord : 0,
    Storm : 2,
    SuperiorIronMan : 2,
    Thor : 0,
    ThorJaneFoster : 0,
    Ultron : 3,
    UnstoppableColossus : 3,
    Venom : 0,
    VenomPool : 0,
    Vision : 3,
    VisionAgeOfUltron : 2,
    Vulture : 2,
    WarMachine : 2,
    WinterSoldier : 0,
    Wolverine : 1,
    X23 : 1,
    YellowJacket : 3,
    Yondu : 2, 
    Medusa : 4,
    Kingpin : 4,
    Hood : 3,
    Mephisto : 3,
    Morningstar : 2, 
    Blade : 1, 
    ThorRagnarok : 2,
    Hela : 2,
    Taskmaster : 3,
    Modok : 4,
    Sentry : 1,
    Void : 4,
    HulkRagnarok : 2,
    Killmonger : 4,
    Sentinel : 3,
    Bishop: 4,
    Sabretooth : 3,
    ProximaMidnight : 1,
    CorvusGlaive : 1,
    CaptainAmericaInfinityWar : 1,
    IronManInfinityWar : 4, 
    Goldpool : 1,
    Domino : 4,
    Masacre : 3,
    Wasp : 3,
    Ghost : 2,
    RedSkull : 2,
    Heimdall : 2,
    Korg : 4,
    OmegaRed : 2,
    EmmaFrost : 3,
    SymbioteSupreme : 2,
    VenomTheDuck : 1,
    Champion : 1,
    Aegon : 1,
    Nightthrasher : 1,
    Darkhawk : 3,
    Thing : 5,
    Diablo : 2,
    Havok : 4,
    MisterSinister: 3,
    CaptainMarvelMovie:2,
    NickFury: 5,
    Annihilus:4,
    HumanTorch:2,
    Ronin:1,
    CullObsidian:1,
    EbonyMaw:4,
    Namor:2,
    InvisibleWoman:3,
    SpiderManStealth:2,
    Mysterio:4,
    Sunspot:1,
    Warlock:3,
    BlackWidowClaireVoyant:2,
    VisionAarkus:4,
    ElsaBloodstone:2,
    ManThing:3,
    Guillotine2099:2,
    DoctorDoom:5,
    MisterFantastic:2,
    SilverSurfer:2,
    SquirrelGirl:2,
    Nova:3,
    Longshot:3,
    Mojo:5,
    WeaponX:5,
    MoleMan:3,
    Terrax:4,
    SorcererSupreme:2,
    StormPyramidX:2,
    BlackWidowDeadlyOrigins:3,
    RedGuardian:1,
    Tigra:4,
    HitMonkey:3,
    Guardian:2,
    Sasquatch:4,
    AirWalker:3,
    Dragonman:4,
    PlatinumPool:2,
    ProfessorX:3,
    Apocalypse:5,
    RedGoblin:2,
    CosmicGhostRider:2,
    HulkImmortal:2,
    AbominationImmortal:4,
    SpiderHam:3,
    Jubilee:2,
    Stryfe:3,
    PsychoMan:2,
    SuperSkrull:2,
    Mangog:4,
    Odin:3,
    SilverCenturion:1,
    JabariPanther:2,
    MisterNegative:5,
    ShangChi:0,
    Purgatory:3,
    Hercules:2,
    Overseer:3,
    AmericaChavez:2,
    Spiderman2099:3,
    PeniParker:4,
    KittyPryde:3,
    Nimrod:4,
    AntiVenom:1,
    Knull:1,
    Empty:0,
}
    
type SigRelevance int

const (
    UN SigRelevance = iota // not imporant
    NA // Needs awakening
    HS // High Sig
)

var sigRelevance = map[HeroVal]SigRelevance {
    Abomination : UN,
    AgentVenom : UN,
    Angela : NA,
    AntMan : UN,
    ArchAngel : UN,
    Beast : UN,
    BlackBolt : NA,
    BlackPanther : UN,
    BlackPantherCivilWar : NA,
    BlackWidow : HS,
    Cable : NA,
    CaptainAmerica : UN,
    CaptainAmericaWWII : UN,
    CaptainMarvel : NA,
    Carnage : HS,
    CivilWarrior : NA,
    Colossus : UN,
    Crossbones : UN,
    Cyclops : UN,
    CyclopsNew : UN,
    DareDevil : UN,
    DareDevilClassic : HS,
    Deadpool : UN,
    DeadpoolX : HS,
    DoctorStrange : HS,
    DoctorVoodoo: HS,
    Dormammu : HS,
    Drax : UN,
    Elektra : UN,
    Electro : UN,
    Falcon : UN,
    Gambit : HS,
    Gamora : UN,
    GhostRider : UN,
    GreenGoblin : UN,
    Groot : UN,
    Guillotine: UN,
    Gwenpool : NA,
    Hawkeye : UN,
    HowardTheDuck : UN,
    Hulk : NA,
    Hulkbuster : UN,
    Hyperion : NA,
    Iceman : HS,
    IronFist : UN,
    IronFistImmortal : UN,
    IronMan : UN,
    IronPatriot : UN,
    JoeFixit : UN,
    Juggernaut : NA,
    KamalaKhan : UN,
    Kang : UN,
    Karnak : HS,
    Loki : NA,
    LukeCage : NA,
    Magik : HS,
    Magneto : UN,
    MagnetoNow : UN,
    MilesMorales : UN,
    MoonKnight : UN,
    Mordo : UN,
    MsMarvel : UN,
    Nightcrawler : UN,
    OldManLogan : NA,
    Phoenix : NA,
    Psylocke : UN,
    Punisher : NA,
    Punisher2099 : UN,
    Quake : UN,
    RedHulk : UN,
    Rhino : UN,
    RocketRaccoon : UN,
    Rogue : UN,
    Ronan : UN,
    ScarletWitch : HS,
    SheHulk : UN,
    SpiderGwen : UN,
    Spiderman : HS,
    SpidermanSymbiote : UN,
    SpidermanStark : UN,
    StarLord : UN,
    Storm : UN,
    SuperiorIronMan : UN,
    Thor : UN,
    ThorJaneFoster : UN,
    Ultron : UN,
    UnstoppableColossus : NA,
    Venom : UN,
    VenomPool : UN,
    Vision : HS,
    VisionAgeOfUltron : UN,
    Vulture : UN,
    WarMachine : UN,
    WinterSoldier : UN,
    Wolverine : NA,
    X23 : UN,
    YellowJacket : UN,
    Yondu : UN, 
    Medusa : NA,
    Kingpin : UN,
    Hood : UN,
    Mephisto : NA,
    Morningstar : UN, 
    Blade : UN, 
    ThorRagnarok : NA,
    Hela : NA,
    Taskmaster : HS,
    Modok : UN,
    Sentry : UN,
    Void : UN,
    HulkRagnarok : UN,
    Killmonger : HS,
    Sentinel : UN,
    Bishop: UN,
    Sabretooth : UN,
    ProximaMidnight : UN,
    CorvusGlaive : NA,
    CaptainAmericaInfinityWar : UN,
    IronManInfinityWar : NA, 
    Goldpool : UN,
    Domino : UN,
    Masacre : UN,
    Wasp : HS,
    Ghost : UN,
    RedSkull : NA,
    Heimdall : UN,
    Korg : HS,
    OmegaRed : HS,
    EmmaFrost : UN,
    SymbioteSupreme : NA,
    VenomTheDuck : UN,
    Champion : NA,
    Aegon : UN,
    Nightthrasher : UN,
    Darkhawk : UN,
    Thing : HS,
    Diablo : UN,
    Havok : UN,
    MisterSinister: UN,
    CaptainMarvelMovie:UN,
    NickFury: NA,
    Annihilus:UN,
    HumanTorch:UN,
    Ronin:UN,
    CullObsidian:UN,
    EbonyMaw:UN,
    Namor:UN,
    InvisibleWoman:NA,
    SpiderManStealth:UN,
    Mysterio:UN,
    Sunspot:UN,
    Warlock:HS,
    BlackWidowClaireVoyant:UN,
    VisionAarkus:NA,
    ElsaBloodstone:UN,
    ManThing:NA,
    Guillotine2099:UN,
    DoctorDoom:NA,
    MisterFantastic:UN,
    SilverSurfer:UN,
    SquirrelGirl:UN,
    Nova:NA,
    Longshot:UN,
    Mojo:UN,
    WeaponX:UN,
    MoleMan:UN,
    Terrax:HS,
    SorcererSupreme:UN,
    StormPyramidX:UN,
    BlackWidowDeadlyOrigins:UN,
    RedGuardian:UN,
    Tigra:UN,
    HitMonkey:UN,
    Guardian:UN,
    Sasquatch:NA,
    AirWalker:UN,
    Dragonman:UN,
    PlatinumPool:UN,
    ProfessorX:NA,
    Apocalypse:UN,
    RedGoblin:UN,
    CosmicGhostRider:UN,
    HulkImmortal:UN,
    AbominationImmortal:UN,
    SpiderHam:NA,
    Jubilee:UN,
    Stryfe:UN,
    PsychoMan:HS,
    SuperSkrull:UN,
    Mangog:NA,
    Odin:UN,
    SilverCenturion:UN,
    JabariPanther:NA,
    KittyPryde:HS,
    Nimrod:NA,
    Empty:UN,
}

var Mystics = map[HeroVal]bool {
  BlackWidowClaireVoyant: true,
  Diablo: true,
  DoctorDoom: true,
  DoctorStrange: true,
  DoctorVoodoo: true,
  Dormammu: true,
  Dragonman: true,
  EbonyMaw: true,
  GhostRider: true,
  Guillotine: true,
  IronFist: true,
  IronFistImmortal: true,
  Juggernaut: true,
  Loki: true,
  Longshot: true,
  Magik: true,
  ManThing: true,
  Mangog: true,
  Mephisto: true,
  Mojo: true,
  Mordo: true,
  Morningstar: true,
  Sasquatch: true,
  ScarletWitch: true,
  SorcererSupreme: true,
  SymbioteSupreme: true,
  Hood: true,
  ThorJaneFoster: true,
  Tigra: true,
  UnstoppableColossus: true,
}

func GetDefensiveSigRelevance(h HeroVal) SigRelevance {
  return sigRelevance[h]
}

// Get the defender level for a given heroval
func GetLevel(val HeroVal) int {
    ret, ok := levels[val]
    if !ok {
        panic(fmt.Sprintf("%v not found", val))
    }
    return ret
}
