// Code generated by "stringer -type=HeroVal"; DO NOT EDIT.

package globals

import "fmt"

const _HeroVal_name = "AbominationAgentVenomAntManArchAngelBeastBlackBoltBlackPantherBlackPantherCivilWarBlackWidowCableCaptainAmericaCaptainAmericaWWIICaptainMarvelCarnageColossusCrossbonesCyclopsCyclopsNewDareDevilDareDevilClassicDeadpoolDeadpoolXDoctorStrangeDoctorVoodooDormammuDraxElektraElectroFalconGambitGamoraGhostRiderGreenGoblinGrootGuillotineGwenpoolHawkeyeHowardTheDuckHulkHulkbusterHyperionIcemanIronFistIronFistImmortalIronManIronPatriotJoeFixitJuggernautKamalaKhanKangKarnakLokiLukeCageMagikMagnetoMagnetoNowMilesMoralesMoonKnightMordoMsMarvelNightcrawlerOldManLoganPhoenixPsylockePunisherQuakeRedHulkRhinoRocketRaccoonRogueRonanScarletWitchSheHulkSpiderGwenSpidermanSpidermanSymbioteSpidermanStarkStarLordStormSuperiorIronManThorThorJaneFosterUltronUnstoppableColossusVenomVenomPoolVisionVisionAgeOfUltronVultureWarMachineWinterSoldierWolverineX23YellowJacketYonduMedusaKingpinHoodCivilWarriorPunisher2099AngelaDoctorOctopusMaxHeroVal"

var _HeroVal_index = [...]uint16{0, 11, 21, 27, 36, 41, 50, 62, 82, 92, 97, 111, 129, 142, 149, 157, 167, 174, 184, 193, 209, 217, 226, 239, 251, 259, 263, 270, 277, 283, 289, 295, 305, 316, 321, 331, 339, 346, 359, 363, 373, 381, 387, 395, 411, 418, 429, 437, 447, 457, 461, 467, 471, 479, 484, 491, 501, 513, 523, 528, 536, 548, 559, 566, 574, 582, 587, 594, 599, 612, 617, 622, 634, 641, 651, 660, 677, 691, 699, 704, 719, 723, 737, 743, 762, 767, 776, 782, 799, 806, 816, 829, 838, 841, 853, 858, 864, 871, 875, 887, 899, 905, 918, 928}

func (i HeroVal) String() string {
	if i < 0 || i >= HeroVal(len(_HeroVal_index)-1) {
		return fmt.Sprintf("HeroVal(%d)", i)
	}
	return _HeroVal_name[_HeroVal_index[i]:_HeroVal_index[i+1]]
}
