
// The seatin package correlates a given hero to his
// defender quality. Note: this used to be based on seatin's 
// defender ranking, but modified given my opinion
// and was not created with any direct input from seatin
package seatin

import . "helloworld/globals"
import "fmt"

var levels = map[HeroVal]int { 
    Abomination : 3,
    AgentVenom : 3,
    Angela : 2,
    AntMan : 2,
    ArchAngel : 0,
    Beast : 0,
    BlackBolt : 0,
    BlackPanther : 0,
    BlackPantherCivilWar : 3,
    BlackWidow : 2,
    Cable : 3,
    CaptainAmerica : 0,
    CaptainAmericaWWII : 0,
    CaptainMarvel : 0,
    Carnage : 0,
    CivilWarrior : 0,
    Colossus : 2,
    Crossbones : 3,
    Cyclops : 0,
    CyclopsNew : 2,
    DareDevil : 0,
    DareDevilClassic : 0,
    Deadpool : 0,
    DeadpoolX : 2,
    DoctorStrange : 4,
    DoctorOctopus : 2,
    DoctorVoodoo: 2,
    Dormammu : 4,
    Drax : 0,
    Elektra : 0,
    Electro : 4,
    Falcon : 0,
    Gambit : 2,
    Gamora : 0,
    GhostRider : 2,
    GreenGoblin : 2,
    Groot : 3,
    Guillotine: 0,
    Gwenpool : 0,
    Hawkeye : 0,
    HowardTheDuck : 2,
    Hulk : 3,
    Hulkbuster : 2,
    Hyperion : 4,
    Iceman : 4,
    IronFist : 0,
    IronFistImmortal : 0,
    IronMan : 0,
    IronPatriot : 0,
    JoeFixit : 0,
    Juggernaut : 4,
    KamalaKhan : 0,
    Kang : 3,
    Karnak : 2,
    Loki : 2,
    LukeCage : 0,
    Magik : 4,
    Magneto : 0,
    MagnetoNow : 0,
    MilesMorales : 4,
    MoonKnight : 2,
    Mordo : 4,
    MsMarvel : 0,
    Nightcrawler : 4,
    OldManLogan : 0,
    Phoenix : 2,
    Psylocke : 0,
    Punisher : 2,
    Punisher2099 : 0,
    Quake : 2,
    RedHulk : 2,
    Rhino : 3,
    RocketRaccoon : 0,
    Rogue : 3,
    Ronan : 0,
    ScarletWitch : 0,
    SheHulk : 0,
    SpiderGwen : 0,
    Spiderman : 4,
    SpidermanSymbiote : 3,
    SpidermanStark : 4,
    StarLord : 0,
    Storm : 2,
    SuperiorIronMan : 2,
    Thor : 0,
    ThorJaneFoster : 0,
    Ultron : 3,
    UnstoppableColossus : 3,
    Venom : 0,
    VenomPool : 0,
    Vision : 3,
    VisionAgeOfUltron : 2,
    Vulture : 2,
    WarMachine : 2,
    WinterSoldier : 0,
    Wolverine : 2,
    X23 : 2,
    YellowJacket : 3,
    Yondu : 3, 
    Medusa : 3,
    Kingpin : 2,
    Hood : 3,
}
    
// Get the defender level for a given heroval
func GetLevel(val HeroVal) int {
    ret, ok := levels[val]
    if !ok {
        panic(fmt.Sprintf("%v not found", val))
    }
    return ret
}
